# Constants for screen and world size
WINDOW_WIDTH, WINDOW_HEIGHT = 1280, 720
WORLD_WIDTH, WORLD_HEIGHT = 1560, 1440

# Player settings
PLAYER_SPEED = 5
PLAYER_SIZE = 50

# Enemy settings
ENEMY_SIZE = 50
ENEMY_SPEED = 2
ENEMY_VISION_RADIUS = 300

# Game settings
NUMBER_OF_OBSTACLES = 25
ENEMY_NUMBER = 2
COOLDOWN_PERIOD = 1500
