# world size
WINDOW_WIDTH, WINDOW_HEIGHT = 1920, 1080
WORLD_WIDTH, WORLD_HEIGHT = 2920, 2080

# player settings
PLAYER_SPEED = 5
PLAYER_SIZE = 50
PLAYER_MAX_HEALTH = 100  # Maximum health for the player

# enemy settings
ENEMY_SIZE = 50
ENEMY_SPEED = 2
ENEMY_VISION_RADIUS = 300

# game settings
NUMBER_OF_OBSTACLES = 25
ENEMY_NUMBER = 10
